{
 "title": "Teste",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Steps(Pass)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Step 1" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": { "filter": "Teste de login(Pass)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 2" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": { "filter": "Validação da home(Pass)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 3" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": { "filter": "Validar pesquisa(Pass)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 4" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": { "filter": "Acesso a ferramenta(Pass)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 5" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": {
      "filter": "Validar criação de páginas(Pass)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 6" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": { "filter": "Validação dos menus(Pass)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 7" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": {
      "filter": "Validação para anexar arquivos(pass)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 8" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": {
      "filter": "Validar a exclusão do anexo (Pass)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Steps(Fails)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Step 1" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": { "filter": "Teste de login(fails)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 2" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": {
      "filter": "Validar criação de páginas(Fails)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 3" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": { "filter": "Validar pesquisa(Fails)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 4" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": { "filter": "Acesso a ferramenta(Fails)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 5" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": {
      "filter": "Validar criação de páginas(Fails)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 6" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": { "filter": "Validação dos menus(Fails)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 7" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": {
      "filter": "Validação para anexar arquivos(Fail)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Step 8" },
     "group": { "filter": "Template/Robot_Raw_Itens" },
     "host": { "filter": "Robo" },
     "item": {
      "filter": "Validar a exclusão do anexo(Fail)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total de fails",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Robot Raw Itens" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Robo" },
     "item": { "filter": "Fail" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}